version: "3"
services:
  cas-server:
    container_name: cas-server
    build: . 
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - "./CAS:/etc/cas"
      - "./cert:/etc/cert"
      - "./logs:/data/logs"
    env_file: .env
